version: "3.8"

services:
  app:
    build:
      # Set the context to the parent directory, so we can add `.tool-versions` to the container
      context: ../
      dockerfile: .devcontainer/Dockerfile
    environment:
      MIX_ENV: dev
    volumes:
      - ../:/workspace/buffphx

    # Overrides default command so things don't shut down after the process ends.
    command: bash -c "sleep infinity"