version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MIX_ENV: dev
    volumes:
      - ../:/workspace
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - default
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PSQL_TRUST_LOCALNET: 'true'
      ENCODING: UTF8
    ports:
      - 5432:5432
    networks:
      - default